Another approach for zsh completion
urfave/cli pull request #1218
Opened 2021-01-14 19:45 UTC by z0rc

## What type of PR is this?

- [ ] bug
- [ ] cleanup  
- [x] documentation
- [x] feature

## What this PR does / why we need it:

I want to open discussion how this project provides completion for zsh. Current situation isn't right and promotes [cargo-cult approach](https://medium.com/@jzelinskie/please-dont-ship-binaries-with-shell-completion-as-commands-a8b1bcb8a0d0) to enable zsh completions.

Completion file shouldn't be sourced. It should provide only completion code (source of `_command` function) for `command`. Ideally this file should be just template/example, where developer should replace `$PROG` with name of binary and distribute it with `_command` name somewhere under project's contrib folder (alongside with man pages, vim syntax etc). As go build system isn't able to properly install this kind of stuff, it's up to package manager (homebrew, dpkg etc) to pick up this `_command` file and put it under correct `$fpath` where zsh can autoload it.

Currently this PR changes only zsh completion example. The documentation needs to be updated too. I can look into if there is agreement with current proposal.

## Special notes for your reviewer:

There is fundamental problem with this project calling "completions" as "_auto_-completions", which are different terms. See https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html and http://zsh.sourceforge.net/Doc/Release/Completion-System.html for correct terminology. You might want to fix this in future.

2021-01-27 18:12 UTC, lynncyrin requested changes
Can you pull in the default branch to fix the failing test please 🙏🏼

2021-01-27 18:13 UTC, lynncyrin commented
@z0rc Can you pull in the default branch to fix the failing test please 🙏🏼

2021-01-29 12:53 UTC, z0rc commented
@lynncyrin done.

This is work in progress, still requires consensus about proposal and documentation updates if proposal accepted. Marked as draft and awaiting your input.

2021-01-29 15:18 UTC, z0rc commented
Also refactored how zsh shell is detected. `$SHELL` shows login shell which is almost always user's current shell, unless they do something weird like launching zsh from bashrc.

2021-08-22 16:29 UTC, closed without merging