make the man page section selectable
urfave/cli pull request #1227
Opened 2021-01-25 13:29 UTC by nmi

## What type of PR is this?

- [ ] bug
- [ ] cleanup  
- [ ] documentation
- [x] feature

## What this PR does / why we need it:

The section number of the man page is fixed to 8.
This number can take other values depending on the usage.

https://www.man7.org/linux/man-pages/man7/man-pages.7.html

This fix adds a new argument to the `ToMarkdown` and `ToMan` methods so that they can be set to arbitrary values.
If you prefer other implementation, please let me know.

## Testing

Existing test code has been reused.

## Release Notes

```release-note
adds a new argument to the `ToMarkdown` and `ToMan` methods so that they can be set to arbitrary section number.
```

2021-01-25 18:08 UTC, lynncyrin requested changes
I strongly recommend adding the 8 as a "default" for people who have an understanding of what the section number represents

2021-01-26 13:41 UTC, nmi commented
@lynncyrin I respect your opinion about the default section number.

Since Go does not support the optional argument, I would like to work on one of the following implementations.
Which one is preferable?

- In addition to `ToMan()`, add a function like `ToManWithSection(section int)`
- Add an attribute to the struct `app` to represent the section number
- Other implementations

2021-01-26 22:43 UTC, lynncyrin commented
@nmi

> In addition to `ToMan()`, add a function like `ToManWithSection(section int)`

This one sounds best!

2021-01-27 14:45 UTC, nmi commented
@lynncyrin Thanks! I've submitted a new patch.

2021-01-27 18:10 UTC, lynncyrin requested changes
Thank you ✨ can you also increase the code coverage? This page will help

https://codecov.io/gh/urfave/cli/pull/1227/diff

2021-01-28 00:45 UTC, nmi commented
@lynncyrin Coverage has improved. Can you please check again?

2021-01-28 03:09 UTC, lynncyrin approved these changes
:shipit:

2021-01-28 12:09 UTC, saschagrunert approved these changes
That's nice, LGTM :+1:

2021-01-28 21:33 UTC, merged