Link to godoc for v2
urfave/cli pull request #1228
Opened 2021-01-27 17:30 UTC by zwass

## What type of PR is this?

- [ ] bug
- [ ] cleanup  
- [x] documentation
- [ ] feature

## What this PR does / why we need it:

This is consistent with the default tag for the repository.

## Release Notes

Does not require a release note

2021-01-27 18:06 UTC, lynncyrin requested changes
The page https://godoc.org/github.com/urfave/cli/v2 404s?

![image](https://user-images.githubusercontent.com/5768468/106034093-50f4bd00-6087-11eb-8133-4958226cb1ed.png)

2021-01-28 00:09 UTC, zwass commented
Ahh, I see. I have the "always use pkg.go.dev" setting on so it works after the redirect. Let's just use the direct link to pkg.go.dev?

2021-01-28 03:10 UTC, lynncyrin approved these changes
:shipit:

2021-01-28 12:09 UTC, saschagrunert approved these changes
LGTM

2021-01-28 21:33 UTC, merged