Allow same flag to be repeated by child commands.
urfave/cli pull request #1245
Opened 2021-02-12 16:14 UTC by ipostelnik

Reading the value or checking for presence looks at the most specific subcommand that includes the flag on the command line.

## What type of PR is this?

- [ ] bug
- [ ] cleanup  
- [ ] documentation
- [x] feature

## What this PR does / why we need it:

Add support for duplicate flags along subcommand chain. This allows the application and (sub)commands to define the same flag. The context for the ultimate action that runs will read the most specific value.

## Which issue(s) this PR fixes:

## Testing

Added a number of units tests to cover these cases. Corrected some of the existing tests to correctly mock operation of the production code.

## Release Notes

(sub)commands can now re-declare flags defined at parent command or the app. This allows these flags to appear in either location on the command-line. During action execution, context will read value provided at most-specific (rightmost) position.

```release-note

```

2021-04-02 16:14 UTC, dearchap commented on context.go
>  func lookupFlagSet(name string, ctx *Context) *flag.FlagSet {
Couldnt you incorporate the resolveFlagDeep logic into this function to retrieve the corresponding flagset ? That would have meant zero changes to existing flag_xxxx src files. Moreover the current code handles the case of lookupFlagSet returning nil which the proposed changes dont handle .

2021-04-02 16:18 UTC, dearchap commented on context.go
> +	err := c.flagSet.Set(name, value)
combine into a single line, if err := c.flagSet.Set(..); err == nil { c.FromFlagSet[name]=true }

2021-04-02 16:22 UTC, dearchap commented on context.go
> +		// now see if value was set externally via environment
why remove the lookupFlag call ?

2021-04-02 16:24 UTC, dearchap requested changes
I dont see any tests written specifically for this change. Can you add some so that its clear that the said functionality works ?

2022-04-19 23:29 UTC, meatballhat commented
@ipostelnik Hello and sorry for the delay and auto-close via stalebot. Are you up for revisiting this work, resolving conflicts, and incorporating changes from feedback?

2022-04-20 17:02 UTC, ipostelnik commented
It has been a while, I will try to rebase this PR on current master and look into comments.

2022-11-28 00:03 UTC, dearchap commented
I am inclined to close this since we have merged persistent flag support in 3.x

2022-11-28 00:03 UTC, closed without merging