Support Help Template overrides for Subcommands
urfave/cli pull request #1312
Opened 2021-11-06 19:48 UTC by ddouglas

## What type of PR is this?

- [X] bug
- [ ] cleanup  
- [ ] documentation
- [ ] feature

## What this PR does / why we need it:

When using the Subcommands, it is currently no possible to override the Subcommand Template that is used due to the Command being overwritten when initializing Context inside of the `RunAsSubcommand` function. I outline everything in #1303. The comment in the code details how I came to the conclusion I came to. Ideally, the Command would not be overridden but set to the Parent Command that houses the Subcommands that are being executed. 

## Which issue(s) this PR fixes:

Fixes #1303

## Special notes for your reviewer:

This is a bandaid at best. I do not expect this PR to be merged. I might update it later with an actual fix, but I just wanted to test my hypothesis, I did that, this works, but ideally, you give Subcommand Context to the `NewContext` Command should the `c.Command` is initialized with the parent command instead of a empty `*cli.Command`

## Release Notes

```release-note
Adds Support for overriding cli.SubcommandHelpTemplate
```

2022-04-26 03:04 UTC, meatballhat commented
@ddouglas Sorry for the big delay 😭 What do you think about adding a new field to `App` such as `CustomSubcommandHelpTemplate` instead of what you have here? This would mean bumping from a "bug" to a "feature" given the increased API surface area, but I think it'd result in fewer surprises in the future.

2022-04-26 11:43 UTC, dearchap commented
@ddouglas Can you add a test case as well ?

2022-08-27 01:13 UTC, dearchap requested changes
Can you update the unit tests for this ?

2022-09-23 20:04 UTC, dearchap commented
@ddouglas I'm going to close this and push another PR with the proper fix/tests.

2022-09-23 20:04 UTC, closed without merging