Feature:(Issue 1334) Add support for uint64slices
urfave/cli pull request #1378
Opened 2022-04-26 23:15 UTC by dearchap

## What type of PR is this?

- feature

## What this PR does / why we need it:

Add support for uint64 slices

## Which issue(s) this PR fixes:

## Special notes for your reviewer:

Please focus on altsrc changes as well, especially the type switch

## Testing

Ran unit tests

## Release Notes

```
Add support for uint64slice flag 

```

2022-04-28 01:39 UTC, meatballhat requested changes
Lovely! 🎉 I noticed one bit of what I assume was leftover debugging and I think the new json altsrc stuff should definitely be covered by tests 👍🏼

2022-04-28 23:29 UTC, dearchap commented on altsrc/flag.go
> +			log.Print(err)
yeah will remove

2022-06-18 14:09 UTC, meatballhat commented
@dearchap Are you up for addressing the conflicts and getting the test coverage above the threshold? No worries if not. I'm happy to take this work to completion.

2022-07-05 12:49 UTC, dearchap commented
@meatballhat Let me take a look

2022-08-13 01:59 UTC, dearchap commented
@meatballhat Done. Can you take a look ?

2022-08-16 13:35 UTC, dearchap commented
@meatballhat Can you take a look at why tests are failing ? I dont quite understand why.

2022-09-05 14:11 UTC, meatballhat commented
@dearchap looks like tests are happy now -- coverage thresholds are still grumpy, but I don't want to be draconian about those checks. Maybe add some coverage threshold wiggle room as part of this PR? e.g.:

2022-09-08 03:20 UTC, Dokiys commented
> @meatballhat Can you take a look at why tests are failing ? I dont quite understand why.

codecov will use the coverage from the base commit. Checks show target coverage need 83.22. You can try [this](https://docs.codecov.com/docs/common-recipe-list#set-status-checks-to-block-coverage) specify a target

2022-09-10 13:40 UTC, dearchap commented
@meatballhat I've fixed the codecov issues. I'm going to merge.

2022-09-10 13:41 UTC, merged