Add App.EnableStrictLookup option
urfave/cli pull request #1434
Opened 2022-07-12 14:21 UTC by icholy

## What type of PR is this?

- feature

## What this PR does / why we need it:

The current behaviour returns a zero value when accessing an undefined flag. This hides programmer errors and has resulted in several bugs on my end.

## Which issue(s) this PR fixes:

https://github.com/urfave/cli/issues/1408

## Testing

I added tests which make sure `Context.Set` and `Context.Value` panic when accessing an undefined flag.

## Release Notes

```release-note
A new `App.EnableStrictLookup` option which causes undefined flag lookups to panic
```

2022-07-16 11:42 UTC, meatballhat requested changes
Thank you for adding this!

I would like to see two changes:
- statically define an `error` type (`cli.ErrStrictFlagLookup`?) that can be reliably checked via funcs like `errors.Is`
- return this `error` instead of using `panic`

2022-07-16 13:48 UTC, icholy commented
Where would I return this error? The flag value getters don't return errors.

2022-07-16 16:08 UTC, meatballhat commented
@icholy yes! Sorry for not being clear about that distinction. What you propose LGTM 🤘🏼

2022-07-16 19:32 UTC, julian7 commented
I'm also wondering whether handling this event via a hook would be more powerful.

Like, instead of having `App. EnableStrictLookup` boolean, we could have an `App.UnknownFlagHandler` or something like that. Then, the implementer can decide whether the app should throw `panic()`, whether it should log it, or perhaps even change context on such an event.

2022-07-16 20:08 UTC, icholy commented
@julian7 that's an interesting idea. Something like this?

``` go
type App struct {
    // ...
    UnknownFlagHandler func(ctx Context, name string)
}
```

2022-07-17 12:20 UTC, meatballhat commented
> I'm also wondering whether handling this event via a hook would be more powerful.

Oooh I like that idea a lot @julian7

2022-08-15 21:04 UTC, closed without merging